import "./globals.css";
import { Montserrat } from "next/font/google";
import Navbar from "./Components/Navbar/Navbar";
import Footer from "./Components/Footer/Footer";
import Trailer from "./Components/Trailer";

const inter = Montserrat({ weight: "500", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body className="relative w-full h-full">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
